### ISSUE TITLE
More Than Questionable Safety

### ISSUE THREAD

**Issue by 200Ethan** [Not316tb/Magma-IaE#6]
How can you say "Magma is 100% safe to use," and "i got sick of seeing all of the other absolute garbage ones out there that either give you a virus" when you also admit to "It was discovered that some are viruses" and to not "use any of the DLLs that come with Magma"? I love that it's open sourced... except that I can't see the viruses that the DLLs apparently are. If you ever update this to become virus free, that would be great.

**Comment by Not316tb** [comment]
Done!
