### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by Eq1s** [Not316tb/Magma-IaE#7]
(https://user-images.githubusercontent.com/95995139/159133369-b7e62a76-a218-4572-b47e-f8e333184da7.png)
windows defender find 5 issues

upd: now.... defender see a backdoor (https://user-images.githubusercontent.com/95995139/159133485-c07430b4-7e19-4fe9-a6cf-42f8d3027f8b.png)
**

**Comment by dye0** [comment]
why would you believe winblows.. disable the defender, it's 100% safe

**Comment by s7davidj** [comment]
at the time this comment was submitted, no. however I cleaned up the source since (the flags came from dependencies)
